### ISSUE TITLE
arm_home() and disarm() no longer working 

### ISSUE THREAD

**Issue by ryanbuckner** [rsnodgrass/pyadtpulse#11]
I've noticed for about a week now that commands to arm and disarm the alarm are not functioning. There's no error message but no action is taken. I can see in my activity log that the user has successfully logged in.

**Comment by bezhermoso** [comment]
Same here. I think it started failing to do anything starting 2022-03-22.

**Comment by ryanbuckner** [comment]
> Looks like the `armDisarm.jsp` endpoint now requires a new param `sat`.

Is that the user fingerprint? or some other value

**Comment by bezhermoso** [comment]
Some other value. Have a PR for this, still need to test for real: https://github.com/rsnodgrass/pyadtpulse/pull/12

**Comment by rsnodgrass** [comment]
@[bezhermoso](https://github.com/bezhermoso)'s change has been merged.

**Comment by ryanbuckner** [comment]
what's the best way to include your fix. Can we do a  `pip3 --force-reinstall pyadtpulse`  ?

**Comment by rsnodgrass** [comment]
That should work. Or if you are using Home Assistant, just uninstall and
reinstall the integration.

**Comment by ryanbuckner** [comment]
i'm using this with Indigo.  Confirmed it's working for me
