### ISSUE TITLE
pre-commit failing

### ISSUE THREAD

**Issue by rlippmann** [rsnodgrass/pyadtpulse#26]
I'm failing the pre-commit hooks with:

          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

which googling shows is an isort issue, but my isort is 5.12

**Comment by rsnodgrass** [comment]
I just temporarily removed isort from the precommit config file.  You should be good if you update.

**Comment by rlippmann** [comment]
Thanks. I haven’t been having problems with commits to HA core, so I’m not sure what the issue is. Although they’ve switched to ruff.

-- Rob

On Apr 21, 2023, at 4:30 PM, Ryan ***@***.***> wrote:

﻿

I just temporarily removed isort from the precommit config file. You should be good if you update.

**Comment by ryanbuckner** [comment]
This fixed the issue
