### ISSUE TITLE
Add rlippmann@ as another PyPi maintainer

### ISSUE THREAD

**Issue by rsnodgrass** [rsnodgrass/pyadtpulse#30]
rlippmann@ can you create an account on PyPi so I can add permissions for you to also publish the pyadtpulse package.

https://pypi.org/manage/project/pyadtpulse/collaboration/

**Comment by rlippmann** [comment]
Sorry, I didn't see this until today.  Was going to make a new release.  I think the link has expired or something.

**Comment by rsnodgrass** [comment]
Can you create a username on PyPi and let me know what it is? Then I can add permissions. Thanks!!!

**Comment by rlippmann** [comment]
It's rlippmann

BTW, you wouldn't happen to know anything about Okta, would you?

**Comment by rsnodgrass** [comment]
Nope :(
