### ISSUE TITLE
Sites list is empty

### ISSUE THREAD

**Issue by ryanbuckner** [rsnodgrass/pyadtpulse#9]
I only have 1 site. When I authenticate and print(adt.sites), I get an empty list back and an error: 

`ADT Pulse accounts with MULTIPLE sites not yet supported!!!
[]`

Could this be because MFA is enabled on my account?  If so, can I remove MFA or work around this?

**Comment by rsnodgrass** [comment]
Yes, because of 2FA.  You must add a new user to your ADT that does not have 2FA enabled (never login again after creating) and use that for accessing your ADT account via tools.

See https://github.com/rsnodgrass/hass-adtpulse/issues/16

**Comment by ryanbuckner** [comment]
Thanks. I created a new user without signing in. Same issues. Looks like others are having the same issue sometimes. I'm not using HA, just through PyCharm.
